import "@/sass/main.scss";
import "@/app/themes/sass/themes.scss";
import type { Metadata } from "next";
import { ThemeContext } from "./themes/context/ThemeContext";

export const metadata: Metadata = {
	title: "Paulo Wells' CV",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ThemeContext> {/* The body tag moved into ThemeContext */}
				{children}
			</ThemeContext>
		</html>
	);
}